services:
  api:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "4001:4000"
    depends_on:
      - prometheus
    environment:
      - API_URL="" # for testing purposes

  prometheus:
    container_name: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: