# Notes
# ----------------
# This file is used to define the services that will be run in the docker-compose stack for testing puposes
# The services are the app, prometheus, and grafana
# app service is the main service that will be monitored
# prometheus service is the monitoring service that will be used to monitor the app service
# grafana service is the visualization service that will be used to visualize the monitoring data
# To run the stack, run the command `docker-compose -f docker-compose-observability-stack.yml up`
# To stop the stack, run the command `docker-compose -f docker-compose-observability-stack.yml down`
# To make a call to the app service within the devcontainer terminal, run the command `curl -v http://host.docker.internal:4001`
# To access the grafana dashboard, open a browser and navigate to `http://localhost:3000` and login with the default credentials `admin:admin`
# To access the prometheus dashboard, open a browser and navigate to `http://localhost:9090`
# To access the app service, open a browser and navigate to `http://localhost:4001`
# ----------------
services:
  api:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "4001:4000"
    depends_on:
      - prometheus
    environment:
      - API_URL="" # Leave this empty for testing purposes. This is the url of the service that the app service will call. This is used to simulate a service that the app service will call.

  prometheus:
    container_name: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: